spring.application.name=code-visualizer

spring.datasource.url=jdbc:mysql://localhost:3306/code_visualizer
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.port=8080

judge0.url=http://192.168.168.128:2358
